module.exports = {
  env: {
    NEXT_PUBLIC_CONTENTFUL_SPACE: 'epm1co0ux6li',
    NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: 'xE3FvIp0HsutAGo_d-O5Z76dDvz053oDCFfk-Z_owWo',
    NEXT_PUBLIC_CONTENTFUL_PREVIEW_TOKEN: 'qSRI-KLqKQi8cXy3iAkzg8UIFCqeOYk-F6cqQDv61Uc',
  }
}